server:
  port: 8080
  servlet:
    context-path: /fb
fb:
  root: /data
spring:
  web:
    resources:
      chain:
        strategy:
          content:
            enabled: true
      cache:
        cachecontrol:
          cache-public: true
          max-age: 24h
