server:
  port: 8080
  servlet:
    context-path: /fb
fb:
  root: /tmp
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      chain:
        strategy:
          content:
            enabled: true
            paths: /**
      cache:
        cachecontrol:
          cache-public: true
          max-age: 24h